# Dependencies
plugins: [jekyll-paginate]

# Features
excerpt_separator: <!--more-->
categories: "quant|finance|maths|physics|crypto|programming|machine-learning"

theme: minima


# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            Scientific Operations
tagline:          'a scientifc approach to operations'
description:      'a scientifc approach to operations'
url:               'https://reasonabledeviations.com'
baseurl:          
imageurl:       '/assets/images/'

author:
  name:           'Dirk Moreno Arias'
  email:        'dirk@morenolabs.com'


# Custom vars
future: TRUE
version:          1.0.0

github:
  repo:           https://github.com/MorenoLabs/ScientificService

social:
    linkedin: https://www.linkedin.com/in/dirk-moreno/
    # twitter: https://twitter.com/robertmartin88

# Structure
paginate:         10

collections:
  notes:
      output: true
      permalink: /notes/:path/
